const highlightPostData = {
    id: 0,
    title: "This is the title",
    shortCaption: "This is the short caption. Lorem ipsum dolor sit amet consectetur adipiscing. This is the short caption. Lorem ipsum dolor sit amet consectetur adipiscing. This is the short caption. Lorem ipsum dolor sit amet consectetur adipiscing.",
    frontImage: "https://via.placeholder.com/900x450.webp/aa3333",
    topic: "Crypto",
    timetoread: '5 min',
    posted: '13/10/2022'
}

const postList = [
    { ...highlightPostData, id: 1 },
    { ...highlightPostData, id: 2 },
    { ...highlightPostData, id: 3 },
    { ...highlightPostData, id: 4 },
    { ...highlightPostData, id: 5 },
    { ...highlightPostData, id: 6 },
    { ...highlightPostData, id: 7 },
    { ...highlightPostData, id: 8 },
    { ...highlightPostData, id: 9 },
    { ...highlightPostData, id: 10 },
    { ...highlightPostData, id: 11 },
    { ...highlightPostData, id: 12 },
    { ...highlightPostData, id: 13 },
    { ...highlightPostData, id: 14 },
    { ...highlightPostData, id: 15 },
    { ...highlightPostData, id: 16 },
    { ...highlightPostData, id: 17 },
    { ...highlightPostData, id: 18 },
    { ...highlightPostData, id: 19 },
    { ...highlightPostData, id: 20 },
    { ...highlightPostData, id: 21 },
    { ...highlightPostData, id: 22 },
    { ...highlightPostData, id: 23 },
    { ...highlightPostData, id: 24 },
    { ...highlightPostData, id: 25 },
    { ...highlightPostData, id: 26 },
    { ...highlightPostData, id: 27 },
    { ...highlightPostData, id: 28 },
    { ...highlightPostData, id: 29 },
    { ...highlightPostData, id: 30 },
    { ...highlightPostData, id: 31 },
    { ...highlightPostData, id: 32 },
    { ...highlightPostData, id: 33 },
]

export { postList, highlightPostData }